platform :ios, '6.0'
    pod 'AFNetworking'
    pod 'JTRevealSidebarDemo', git: 'https://github.com/felipecsl/JTRevealSidebarDemo'
    pod 'Facebook-iOS-SDK'
    pod 'GoogleAnalytics-iOS-SDK', '~> 2.0beta4'
